language: cpp
before_script:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - mkdir repo
  - cd repo
  - gclient config --unmanaged https://github.com/lukas-w/pdfium.git
  - gclient sync
  - cd pdfium
script:
  - sed -i 's/static_library("pdfium")/shared_library("pdfium")/' BUILD.gn
  - cp $TRAVIS_BUILD_DIR/args.gn .
  - gn gen .
  - ninja pdfium
